apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-courses
  labels:
    app: training-courses
spec:
  replicas: 3
  selector:
    matchLabels:
      app: training-courses
  template:
    metadata:
      labels:
        app: training-courses
    spec:
      containers:
      - name: training-courses
        image: 474668393194.dkr.ecr.us-east-1.amazonaws.com/training-courses:latest
        ports:
        - containerPort: 80
        env:
        - name: DB_CONNECTION
          value: "mysql"
        - name: DB_HOST
          value: "127.0.01"  # Replace with your MySQL service name
        - name: DB_PORT
          value: "3306"
        - name: DB_DATABASE
          value: "training-courses"
        - name: DB_USERNAME
          value: "root"
        - name: DB_PASSWORD
          value: ""
