apiVersion: v1
kind: Service
metadata:
  name: training-courses
spec:
  type: LoadBalancer  # Change to ClusterIP if you don't need external access
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: training-courses