services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Expose the app on port 8080
    environment:
      DB_DATABASE: ${DB_DATABASE}
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3309:3308" # MySQL port mapping
    environment:
      MYSQL_DATABASE: training-courses
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: {}
