services:
  # Database server
  127.0.0.1:
    image: mysql:8.0
    ports:
      - 3309:3308
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: {}
