name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: training-courses
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
          - 3306:3306

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo, pdo_mysql, xml
        extensions: mbstring, bcmath, sqlite3  # Add necessary extensions
        coverage: none
        ini-values: |
          memory_limit=512M
          post_max_size=32M

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Copy .env file
      run: cp .env.example .env

    - name: Update .env with MySQL settings
      run: |
        sed -i 's|DB_CONNECTION=.*|DB_CONNECTION=mysql|' .env
        sed -i 's|DB_HOST=.*|DB_HOST=127.0.0.1|' .env
        sed -i 's|DB_PORT=.*|DB_PORT=3306|' .env
        sed -i 's|DB_DATABASE=.*|DB_DATABASE=training-courses|' .env
        sed -i 's|DB_USERNAME=.*|DB_USERNAME=root|' .env
        sed -i 's|DB_PASSWORD=.*|DB_PASSWORD=|' .env

    - name: Generate application key
      run: php artisan key:generate

    - name: Run Laravel migrations
      run: php artisan migrate --force

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Node.js dependencies
      run: npm install
      
    - name: Clear caches
      run: |
        php artisan config:clear
        php artisan cache:clear
        php artisan route:clear
        php artisan view:clear 

      - name: Run tests
        run: |
          php artisan key:generate
          php artisan migrate --env=testing --force  # Set up the testing database
          php artisan config:cache  # Cache configuration
          ./vendor/bin/phpunit --configuration phpunit.xml --env=testing  # Run PHPUnit tests

    - name: Build frontend assets
      run: npm run build

    - name: Deploy the e-learning platform
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
